name: BasedHits
version: ${project.version}
main: homebrew.basictrades.BasicTrades
api-version: 1.13
authors: [Ryxian]
description: Item based economy with features such as hits and auctions.
commands:
  hit:
    description: Allows a player to place a hit on another player
    usage: /<command>
    aliases: [hits, bounty, bounties]
    permission: BasedHits.hit
  view:
    description: Allows a player to view a hit on another player
    usage: /<command>
    permission: BasedHits.view
permissions:
  BasedHits.hit:
    description: Allows you to use the /hit command
    default: true
  BasedHits.view:
    description: Allows you to use the /view command
    default: true
  BasedHits.claim:
    description: Allows you to claim a bounty
    default: true
  BasedHits.broadcast:
    description: Allows you to see announcements of hits
    default: true
  BasedHits.anonymous.hit:
    description: Allows a player to have their hits hidden
    default: false
  BasedHits.anonymous.claim:
    description: Allows a player to have a claim hidden
    default: false